services:
  # 1. Database
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - contrix_net

  # 2. Redis (Message Queue)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - contrix_net

  # 3. WAHA (WhatsApp API)
  waha:
    image: devlikeapro/waha:latest
    restart: always
    # IMPORTANT: Chrome needs shared memory to render QR codes
    shm_size: 2g 
    environment:
      - WHATSAPP_DEFAULT_ENGINE=NOWEB
      - WAHA_PRINT_QR=False
      - WAHA_API_KEY=secret
      # Add this to ensure the engine starts correctly
      - WAHA_SESSION_TEMP_DIRECTORY=/app/.waha/temp
      # Enable Store for Contacts/Groups
      - WHATSAPP_NOWEB_STORE_ENABLED=True
      - WAHA_NOWEB_STORE_ENABLED=True
      - WHATSAPP_NOWEB_STORE_FULL_SYNC=True
      - WAHA_NOWEB_STORE_FULL_SYNC=True
    volumes:
      - waha_data:/app/.waha
    ports:
      - "3000:3000"
    networks:
      - contrix_net

  # 3b. WAHA 2 (Secondary Node)
  waha2:
    image: devlikeapro/waha:latest
    restart: always
    shm_size: 2g 
    environment:
      - WHATSAPP_DEFAULT_ENGINE=NOWEB
      - WAHA_PRINT_QR=False
      - WAHA_API_KEY=secret
      - WAHA_SESSION_TEMP_DIRECTORY=/app/.waha/temp 
    volumes:
      - waha_data2:/app/.waha
    ports:
      - "3002:3000"
    networks:
      - contrix_net

  # 4. Backend API (Django)
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - db
      - redis
    networks:
      - contrix_net

  # 5. Celery Worker (Background Tasks)
  celery:
    build: ./backend
    command: celery -A contrix_backend worker -l info
    volumes:
      - ./backend:/app
    environment:
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - backend
      - redis
    networks:
      - contrix_net

  # 6. Frontend (Next.js)
  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:3000" # Map host 3001 to container 3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - contrix_net

volumes:
  postgres_data:
  waha_data:
  waha_data2:

networks:
  contrix_net:
    driver: bridge